# Generated by Django 4.2.7 on 2025-01-15 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('inactive', 'Player is inactive or not engaged in any activity'), ('in_queue', 'Player is in a matchmaking queue'), ('pending', 'Player is expected to join a game'), ('waiting_for_players', 'Player is waiting for other players to join the game'), ('loading_game', 'Player is waiting for the game to load'), ('in_game', 'Player is currently playing in a game'), ('spectate', 'Player is currently spectating a game')], default='inactive', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WinRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.gamemode')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for players to join'), ('loading', 'Players are loading game assets and configurations'), ('in_progress', 'Game currently in progress'), ('aborting', 'Game has been aborted'), ('aborted', 'Game has been aborted'), ('finished', 'Game has finished')], default='waiting', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=42, null=True)),
                ('game_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.gamemode')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.gameinstance')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.player')),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.CreateModel(
            name='ModifiersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.gameinstance')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.modifiers')),
            ],
            options={
                'unique_together': {('game', 'modifier')},
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.gameinstance')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.team')),
            ],
            options={
                'unique_together': {('game', 'team')},
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.gameinstance')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.team')),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
    ]
