# Generated by Django 4.2.7 on 2024-10-09 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('usernames', models.JSONField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting for players'), ('in_progress', 'Game in progress'), ('aborted', 'Game aborted'), ('finished', 'Game finished')], default='waiting', max_length=20)),
                ('scores', models.JSONField(default=dict)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('game_duration', models.DurationField(blank=True, null=True)),
                ('game_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_mode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('games', models.JSONField(default=dict)),
            ],
        ),
    ]
