# Generated by Django 4.2.7 on 2024-10-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('inactive', 'Player is inactive or not engaged in any activity'), ('in_queue', 'Player is in a matchmaking queue'), ('pending', 'Player is expected to join a game'), ('waiting_for_players', 'Player is waiting for other players to join the game'), ('loading_game', 'Player is waiting for the game to load'), ('in_game', 'Player is currently playing in a game'), ('spectate', 'Player is currently spectating a game'), ('in_private_room', 'Player is currently in a private room')], default='inactive', max_length=20),
        ),
    ]
