# Generated by Django 4.2.7 on 2024-11-12 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstance',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='gameinstance',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='gameinstance',
            name='usernames',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_history',
        ),
        migrations.CreateModel(
            name='PlayerGameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.gameinstance')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.player')),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.gameinstance')),
            ],
            options={
                'unique_together': {('game', 'team_name')},
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.gameinstance')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.player')),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
    ]
