# Generated by Django 4.2.7 on 2024-10-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='teams',
            field=models.JSONField(default=dict),
        ),
    ]
