# Generated by Django 4.2.7 on 2024-10-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_gameinstance_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='admin_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
