# Generated by Django 4.2.7 on 2024-11-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_remove_gameinstance_scores_remove_gameinstance_teams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='game_mode',
            field=models.CharField(max_length=30),
        ),
    ]
