# Generated by Django 4.2.7 on 2024-10-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0003_gameinstance_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='games',
        ),
        migrations.AddField(
            model_name='player',
            name='game_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('inactive', 'Player is inactive or not engaged in any activity'), ('in_queue', 'Player is in a matchmaking queue'), ('pending', 'Player is expected to join a game'), ('waiting_for_players', 'Player is waiting for other players to join the game'), ('loading_game', 'Player is waiting for the game to load'), ('in_game', 'Player is currently playing in a game')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for players to join'), ('loading', 'Players are loading game assets and configurations'), ('in_progress', 'Game currently in progress'), ('aborted', 'Game has been aborted'), ('finished', 'Game has finished')], default='waiting', max_length=20),
        ),
    ]
