# Generated by Django 4.2.7 on 2024-10-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0005_alter_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='winner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
