# Generated by Django 4.2.7 on 2024-10-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0006_alter_gameinstance_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstance',
            name='game_duration',
        ),
    ]
