# Generated by Django 4.2.7 on 2024-10-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0007_remove_gameinstance_game_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstance',
            name='admin_id',
        ),
    ]
