# Generated by Django 4.2.7 on 2024-09-23 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0004_friendship_customuser_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('friend_request_sent', 'Friend request sent'), ('friend_request_received', 'Friend request received'), ('accept_friend_request', 'Accept friend request'), ('friend_request_accepted', 'Friend request accepted'), ('reject_friend_request', 'Reject friend request'), ('friend_request_rejected', 'Friend request rejected')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted')], db_index=True, default='PE', max_length=2),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['status', 'from_user'], name='authenticat_status_cb0801_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['status', 'to_user'], name='authenticat_status_29dc3f_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
